#!/usr/bin/env php
<?php
//require(__DIR__ . '/vendor/autoload.php');
//require(__DIR__ . '/vendor/yiisoft/yii2/Yii.php');
require(__DIR__ . '/src/Autoload.php');
$config = require(__DIR__ . '/config/config.php');
$app = new \Rimato\SqlMongo\base\Application($config);
$app->run($argv[1]);

exit;